### ISSUE TITLE
Segmentation fault  (core dumped)

### ISSUE THREAD

**Issue by qussai96** [weberlab-hhu/Helixer#109]
Hello,

I am running Helixer on a group of plant genomes. I was able to successfully annotate all of them except three genomes where I had the following error:

```

File "h5py/_objects.pyx", line 201, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (file write failed: time = Fri Dec 15 21:43:00 2023
, filename = '/tmp/tmpfvfk8bu0/tmp_predictions_Tintermedium.h5', file descriptor = 6, errno = 28, error message = 'No space left on device', buf = 0x343aa4860, total write size = 309750, bytes this sub-write = 309750, bytes actually written = 18446744073709551615, offset = 0)
/var/spool/slurm/d/job70405/slurm_script: line 19: 2998044 Segmentation fault      (core dumped) ~/Tools/Helixer-main/Helixer.py --lineage land_plant --fasta-path $genome --species $Species --gff-output-path $Work_Dir/$Species.helixer.gtf
```

The server has plenty of available storage space. Can you please let me know what can cause this issue?  And how can I solve it?

Cheers,

**Comment by soi** [comment]
Hello @qussai96, 

it looks like the slurm job ran out of disk space.

Best, 
Felix

**Comment by qussai96** [comment]
Thank you @soi for the response.
I have an available disk space of 2 terabytes. but it still seems insufficient for Helixer to handle large genomes (exceeding 10 Gb).

best,
Qussai

**Comment by soi** [comment]
@qussai96 splitting the FASTA into a few parts on chromosome level should be a way to solve the problem.

Best,
Felix

**Comment by qussai96** [comment]
Thank you @soi. I am planning to apply this approach and merge the predictions afterwards.

Best,
Qussai

**Comment by felicitas215** [comment]
Hello @qussai96,
I encountered a similar error once. The disk space in your systems default temporary directory ``/tmp`` is the problem. Helixer creates a few temporary files and a temporary sub-directory in your systems default temporary directory. This default directory has sometimes not enough space for large temporary files. Helixer allows for setting a different temporary directory with ``--temporary-dir``, if you want to try a different approach without splitting the fasta files.
Best,
Felicitas

**Comment by qussai96** [comment]
Thanks @felicitas215 for the great tip! I will definitely try the --temporary-dir flag.

best,
Qussai

**Comment by mankiddyman** [comment]
> Hello @qussai96, I encountered a similar error once. The disk space in your systems default temporary directory `/tmp` is the problem. Helixer creates a few temporary files and a temporary sub-directory in your systems default temporary directory. This default directory has sometimes not enough space for large temporary files. Helixer allows for setting a different temporary directory with `--temporary-dir`, if you want to try a different approach without splitting the fasta files. Best, Felicitas

GOAT
