### ISSUE TITLE
Inference after training with RNAseq data

### ISSUE THREAD

**Issue by hjjansen** [weberlab-hhu/Helixer#111]
Hello,
Thank you for creating this genome annotation tool. It is a massive improvement when compared to annotation pipelines (we've used maker before).
Currently I have the genome of the King cobra at hand. I've used Helixer to annotate this genome and when I looked at the gff file I noticed that a cluster of toxin genes was was not complete. Some genes for which there is clearly expression are missing while other ones are perfectly annotated.
Since we have RNAseq data I fine-tuned the vertebrate model with this data according to the fine-tune manual. Subsequence length was 213840.
This all worked fine.
But when I want to do inference using this model it produces the following traceback
Command:
`HybridModel.py --overlap --batch-size 9 --val-test-batch-size 9 -v --test-data Oh_v2.8-predictions_training.h5 --load-model-path Oh_v2.8_best_tuned_rnaseq_model.h5 --pretrained-model-path /home/helixer_user/.local/share/Helixer/models/vertebrate/vertebrate_v0.3_m_0080.h5 --input-coverage --coverage-norm log --post-coverage-hidden-layer`
Traceback:
`Traceback (most recent call last):
  File "/usr/local/bin/HybridModel.py", line 133, in <module>
    model.run()
  File "/usr/local/lib/python3.8/dist-packages/helixer/prediction/HelixerModel.py", line 1009, in run
    model.load_weights(self.load_model_path)
  File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/src/backend.py", line 4361, in _assign_value_to_variable
    variable.assign(value)
ValueError: Cannot assign value to variable ' dense_1/kernel:0': Shape mismatch.The variable shape (16, 36), and the assigned value shape (16, 72) are incompatible.`
I'm using the provided docker container to run Helixer.
I tried to figure out what I'm doing wrong but I'm not getting far. I can indeed see that the fine-tuned model has `dense_1/kernel:0` in `model_weights` with dimension 16 x 72 whereas the vertebrate model has `dense/kernel:0` with dimension 256 x 72.
I also noticed that in HelixerModel.py", line 1008 the coverage is added by calling `insert_coverage_before_hat`
I'm wondering if this is where the dimension 16 x 36 is coming from.
My Oh_v2.8-predictions_training.h5 file does indeed have `evaluation/rnaseq_coverage`.
I hope that you can give some guidance.
Many thanks,
Hans

**Comment by alisandra** [comment]
Hi Hans,

Thanks for interest in Helixer, props to your bravery for venturing into the 'experimental' docs, and thanks for the info on how it went so far. 

I don't have enough info to give you a confident answer. But some thoughts anyway:

I think the error message is trying to tell you that the weights it is loading in for layer `dense/kernel:0` don't match the size setup based on the command line call at inference inference time.

>There is a longer story on why these shapes couldn't be pulled dynamically from the loaded model... but I haven't fixed it yet and it isn't as easy as I should think it would be. 

So, first sanity check. Did you include `--post-coverage-hidden-layer` at training time?  If not, then don't include it at inference either. In general, all parameters controlling shape / model architecture will need to match, so you can make a sanity check for any other discrepancies too. But there aren't so many that can differ at this stage and `--post-coverage-hidden-layer` is one of them. 

Otherwise, I can probably help more if I get a full record of commands from first prediction, through fine tuning and inference.

**Comment by hjjansen** [comment]
Hi Alisandra,
Sorry, bit of a long post but I hope it'll make things more clear.
I indeed used `--post-coverage-hidden-layer` both at training and inference time. Below are the commands as used to get to the inference command.
First the three step process:
```
fasta2h5.py --subsequence-length 213840 --species Ophiophagus_hannah --h5-output-path Ophiophagus_hannah_genome_v2.8.h5 --fasta-path Ophiophagus_hannah_genome_v2.8.fasta
HybridModel.py --load-model-path /home/helixer_user/.local/share/Helixer/models/vertebrate/vertebrate_v0.3_m_0080.h5 --test-data Ophiophagus_hannah_genome_v2.8.h5 --prediction-output-path Oh_v2.8_predictions.h5 --overlap --subsequence-length 213840 --overlap-offset 106920 --overlap-core-length 160380 --batch-size 9 --val-test-batch-size 9 -v
helixer_post_bin Ophiophagus_hannah_genome_v2.8.h5 Oh_v2.8_predictions.h5 100 0.1 0.8 60 Ophiophagus_hannah_genome_v2.8.01.gff3
```
Then preparing the data to use for training and adding coverage.
There is only one old unstranded PE dataset I could use. I have long read cDNA data but that is single read and can't be included (I still want to look at that because long reads show nicely how exons are connected in a gene):
```
import2geenuff.py --fasta Ophiophagus_hannah_genome_v2.8.fasta --gff3 Ophiophagus_hannah_genome_v2.8.01.gff3 --db-path Ophiophagus_hannah_v2.8.sqlite3 --log-file Ophiophagus_hannah_v2.8_import.log --species Ophiophagus_hannah
geenuff2h5.py --h5-output-path Oh_v2.8-predictions_training.h5 --input-db-path Ophiophagus_hannah_v2.8.sqlite3 --subsequence-length 213840
python3 /home/helixer_user/Helixer/helixer/evaluation/add_ngs_coverage.py  -s Ophiophagus_hannah --unstranded --bam SRR1821260_vs_Ophiophagus_hannah_genome_v2.8_sorted.bam --h5-data Oh_v2.8-predictions_training.h5 --dataset-prefix rnaseq --threads 1
```
And creating the training and evaluation datasets:
```
python3 filter-to-most-certain.py --write-by 6415200 --h5-to-filter Oh_v2.8-predictions_training.h5 --predictions Oh_v2.8_predictions.h5 --keep-fraction 0.2 --output-file Oh_v2.8_filtered.h5; 
mkdir Oh_fine_tuning_data_dir_v2.8
python3 n90_train_val_split.py --write-by 6415200 --h5-to-split Oh_v2.8_filtered.h5 --output-pfx Oh_fine_tuning_data_dir_v2.8/
```
Training the vertebrate model to include coverage information:
```HybridModel.py -v --batch-size 9 --val-test-batch-size 9 --class-weights "[0.7, 1.6, 1.2, 1.2]" --transition-weights "[1, 12, 3, 1, 12, 3]" --predict-phase --learning-rate 0.0001 --resume-training --fine-tune --load-model-path /home/helixer_user/.local/share/Helixer/models/vertebrate/vertebrate_v0.3_m_0080.h5 --input-coverage --coverage-norm log --post-coverage-hidden-layer --data-dir Oh_fine_tuning_data_dir_v2.8 --save-model-path Oh_v2.8_best_tuned_rnaseq_model.h5```
The training finished in 30 epoch's These commands did not create any error messages. The only thing I see is this:
```
Data config:
[{'geenuff_commit': 'commit not found, version: 0.3.0', 'helixer_commit': 'commit not found, version: 0.3.2', 'input_path': 'Ophiophagus_hannah_v2.8.sqlite3', 'timestamp': '2024-01-11 14:37:31.024795'}]

Test data shape: (14764, 213840)

Intergenic test seqs: 1.52%
Fully correct test seqs: 3.01%

2024-01-15 07:56:53.021275: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-15 07:56:53.021534: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-15 07:56:53.021717: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-15 07:56:53.622282: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-15 07:56:53.622555: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-15 07:56:53.622749: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-15 07:56:53.622889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10070 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Ti, pci bus id: 0000:01:00.0, compute capability: 8.6
Number of devices: 1
```
I tried to solve that warning by using the solution provided in [here](https://github.com/tensorflow/tensorflow/issues/42738#issuecomment-922422874):
`for a in /sys/bus/pci/devices/*; do echo 0 | sudo tee -a $a/numa_node; done`
But I got a `Read-only file system` error (I'm running the docker container). The GPU is still utilized as shown by `nvidia-smi`.

And in the inference stage I'm getting the dimension mismatch.
`HybridModel.py --overlap --batch-size 9 --val-test-batch-size 9 -v --test-data Oh_v2.8-predictions_training.h5 --load-model-path Oh_v2.8_best_tuned_rnaseq_model.h5 --pretrained-model-path /home/helixer_user/.local/share/Helixer/models/vertebrate/vertebrate_v0.3_m_0080.h5 --input-coverage --coverage-norm log --post-coverage-hidden-layer`

**Comment by alisandra** [comment]
Hi Hans,

Thanks for all the info, that helps!

Can you try adding `--predict-phase` at inference time?

Let me know how it goes, and if it fixes it, I'll update the docs to help the next person.

**Comment by alisandra** [comment]
Oh, and one other thing:

I'm not 100% sure what you mean here
> long read cDNA data but that is single read 

But single end reads and full transcript (e.g. PacBio IsoSeq) data should also be possible to use.

So if you tried and it did not work, feel free to open an issue for that too.

**Comment by hjjansen** [comment]
Hi Alisandra,
Adding `--predict-phase` did the trick! `HybridModel.py` and `helixer_post_bin` executed normally without errors.
And with regards to the type of RNAseq data: That was my bad. I thought I read somewhere that I could only use paired end data.
I will fine-tune with the other RNAseq data as well. This first round of fine-tuning made the predictions actually worse, so I'm most likely introducing a terrible bias by using only one sample/tissue.
But at least the procedure is working so I can only improve on this result!
Many thanks for your help!
Have a good weekend,
Hans
P.S. Shall I close this issue?

**Comment by alisandra** [comment]
Great, `--predict-phase` has been added to the docs now, thanks for the feedback!

As to performance, well it's experimental, and there's no best practice I can share yet. 
In so far as you feel like experimenting, the things I can say with some confidence is that having a training set representative of what you want the network to learn is critical, as well as avoiding overfitting. 

Here's a few things you can think of adjusting (if interested).

During data prep:
- definitely agree that increasing data quantity & quality, in so far as possible, sounds like a very good idea.
- you can adjust the `--keep-fraction` when filtering, which is an amount/quality trade off (I don't have the 'right' answer, but this will certainly effect final results)
- since you're especially interested in a specific set of genes, you could go in more manually to check that the toxin genes "that are perfectly annotated" do end up in the training set, or at least that the region containing the ones that are missing, do not. 

During training to avoid overfitting you can:
- reduce the learning rate
- reduce the maximum number of epochs

Good luck, and if you learn anything interesting, feedback is always welcome!
