### ISSUE TITLE
How to train the training models for non-listed species

### ISSUE THREAD

**Issue by JiantaoZhao426** [weberlab-hhu/Helixer#113]
Hi,

I'm wondering is there any way to generate the train model for a given non-listed species provided by Helixer? In my case, I already have one accession with high quality assembly and annotation and have about ~30 genomes assembled and waiting for gene annotation.

Best,

Jiantao

**Comment by alisandra** [comment]
Hi Jiantao, 

Thanks for your question and interest!

Do I get it right that you wish to fine-tune the model on the one existing high quality annotation, and then run inference on the other 30? If your species of interest somewhat is "close" to any of the available groups (vertebrate, invertebrate, plant, fungi) but you're not happy with the raw performance, you might try [fine tuning](https://github.com/weberlab-hhu/Helixer/blob/main/docs/fine_tuning.md). 

Regardless, I would strongly recommend running Helixer "as is" with the closest model first, both to make sure the basics are working and set baseline expectations / track progress.

Given that you already have high quality gene models; I assume that you would probably want to use those models; not pseudolabels from Helixer for fine tuning, so the process would differ from the linked instructions somewhat. I would imagine it might look something like this

### convert your annotation.gff3 to an h5 file (numeric matrices that the model can train on)

```
# read into the GeenuFF database
import2geenuff.py --fasta <your_genome.fa> --gff3 <annotation.gff3> \
  --db-path <your_species>.sqlite3 --log-file <your_species_import>.log \
  --species <speces_name_or_prefix>
# export to numeric matrices
geenuff2h5.py --h5-output-path <your_species_training_data>.h5 \
  --input-db-path <your_species>.sqlite3 
  ```
  
  split the resulting data into a train / val set 
  
  ```
mkdir <fine_tuning_data_dir>
python3 n90_train_val_split.py --write-by 6415200 \
    --h5-to-split <filtered.h5> --output-pfx <fine_tuning_data_dir>/
# note that any directories in the output-pfx should exist
# it need not be an empty directory, but it is the simplest here

# check that training and validation files were created and are non-empty
ls -sSh <fine_tuning_data_dir>/
  ```
  
and then one of 
  
### fine tune the _whole_ model
```
HybridModel.py -v --batch-size 50 --val-test-batch-size 100 -e200 \
  --class-weights "[0.7, 1.6, 1.2, 1.2]" --transition-weights "[1, 12, 3, 1, 12, 3]" \
  --predict-phase --learning-rate 0.00003 --resume-training \
  --load-model-path <$HOME/.local/share/Helixer/models/land_plant/land_plant_v0.3_a_0080.h5> \
  --data-dir <fine_tuning_data_dir> --save-model-path <tuned_for_your_species_best_model.h5>
```

or training with just one genome I'd be slightly in favor of

### fine tune just the last layers of the model

```
# model architecture parameters are taken from the loaded model
# but training, weighting and loss parameters do need to be specified
# appropriate batch sizes depend on the size of your GPU
HybridModel.py -v --batch-size 50 --val-test-batch-size 100 -e200 \
  --class-weights "[0.7, 1.6, 1.2, 1.2]" --transition-weights "[1, 12, 3, 1, 12, 3]" \
  --predict-phase --learning-rate 0.0001 --resume-training --fine-tune \
  --load-model-path <$HOME/.local/share/Helixer/models/land_plant/land_plant_v0.3_a_0080.h5> \
  --data-dir <fine_tuning_data_dir> --save-model-path <tuned_for_your_species_best_model.h5>
  ```

### misc  
Note that I neither tested nor optimized those commands so small errors are expected. Moreover, as with all of fine-tuning, this is an experimental application of Helixer. Feel free to ask more questions and please do let us know how it goes / give feedback if you're willing. 

Make sure to replace everything in and including these brackets `<>` with appropriate paths / file names

You can find some information on what the above commands do, and importantly when you want to fine tune
the whole network vs only the final layers in the [fine tuning documentation](https://github.com/weberlab-hhu/Helixer/blob/main/docs/fine_tuning.md) mentioned above.

**Comment by alisandra** [comment]
Hi Jiantao,

So while we write a single value for a transcription start or end position to be able to represent a gene model in a gff format, this is a convenient (and useful) simplification of what's actually a probability distribution for transcript start/ end position and therefore _exact_ matches are rare, beit due to biological variation, measurement uncertainty, or both. 

Generally when one looks for exact matches in structural gene annotations, it at most makes sense to compare the coding sequence, not the whole transcript. 

Cheers,
Alisandra

**Comment by Toffeeladd** [comment]
Hi Guys,

I am attempting to annotate 39 Aegilops tauschii accessions using Helixer and the land_plant model. Currently Helixer is predicting between 110-120k genes for each accession. The species has a good reference genome/annotation (Diploid, 4GB with around 62k genes) so Helixer is predicting almost double the number of genes. (I have checked the ploidy level of the accessions and they are all still diploid so this is not causing the increase in gene number).

I have been trying to fine tune the model according to this thread in attempt to get the gene prediction closer to that of the reference genome. I am using the Aegilops_tauschii NCBI reference genome and annotation for this however I am encountering errors on the final fine tuning step. The final model is not produced and there is an error in the log file "IndexError: list index out of range" I attach the log file below:

``` 
export HELIXER_SIF=/users/bop22ngb/helixer-docker_helixer_v0.3.2_cuda_11.8.0-cudnn8.sif

apptainer exec ${HELIXER_SIF} HybridModel.py -v --batch-size 50 --val-test-batch-size 100 -e200 \
  --class-weights "[0.7, 1.6, 1.2, 1.2]" --transition-weights "[1, 12, 3, 1, 12, 3]" \
  --predict-phase --learning-rate 0.0001 --resume-training --fine-tune \
  --load-model-path /users/bop22ngb/.local/share/Helixer/models/land_plant/land_plant_v0.3_a_0080.h5 \
  --data-dir fine_tuning_data --save-model-path /users/bop22ngb/.local/share/Helixer/models/land_plant/Aegilops_tauschii_model.h5 
```

[slurm-1278449.txt](https://github.com/weberlab-hhu/Helixer/files/14065557/slurm-1278449.txt)

Everything seems to have run as normal with the previous steps however I did notice that on the first step converting my gff3 to h5 file my sqlite db was saved as a partial index. i.e. Aegilops_tauschii.sqlite.partial. I wonder if this is causing the indexing error in the final step when trying to fine tune the model. I attach log file below:

``` 
export HELIXER_SIF=/users/bop22ngb/helixer-docker_helixer_v0.3.2_cuda_11.8.0-cudnn8.sif

# read into the GeenuFF database

apptainer exec ${HELIXER_SIF} import2geenuff.py --fasta GCA_002575655.2_Aet_v5.0_genomic.fna --gff3 /mnt/parscratch/users/bop22ngb/Aegilops/model_training/Aegilops_tauschii_ncbi/data/GCF_002575655.2/genomic.gff  \
  --db-path Aegilops_tauschii.sqlite3 --log-file Aegilops_tauschii.log \
  --species Aegilops_tauschii

# export to numeric matrices
apptainer exec ${HELIXER_SIF} geenuff2h5.py --h5-output-path Aegilops_tauschii.h5 \
  --input-db-path Aegilops_tauschii.sqlite3.partial
``` 
[slurm-1239186.txt](https://github.com/weberlab-hhu/Helixer/files/14065628/slurm-1239186.txt)

Please could you give me any advice on this issue and how I can fine tune the model. Could you also please advise me that this is a logical approach to solve the issue I am having with the overprediction of genes. Thank you again for such a great software!

Best,
Noah

**Comment by alisandra** [comment]
Hi Noah!

Thanks for your interest and clear question!

First, yes, this thread is very likely a good strategy from what you describe (by my best guess anyway, as all of fine tuning remains a bit experimental). That said, for the sake of trying simple things first, you could also try setting the --peak-threshold higher (default, is 0.8, so you could try e.g. 0.9), which increases the precision some.

On fine tuning - if you have the .partial file, then the import2geenuff.py didn't run through. The.partial output is there for debugging purposes, but it's certainly incomplete and may even be empty.
Import2geenuff.py uses very strict gff3 parsing, so as not to "mis parse" and then erroneously train on anything not in the offial gff3 spec/not explicitly handled correctly. The idea being to fail loudly and make a human check early. This strictness can also be frustrating, I know. 

The short current advice is to look at the final error in the import2geenuff.py stderr, and see if you can remove whatever the parser is comlaining about from the gff3 file entirely, at least if the error does not pertain to protein coding genes. You can also find an extremely rough record of how we imported ensembl genomes here: https://github.com/weberlab-hhu/helixer_scratch/blob/master/data_scripts/gff_cleaning/cleaning_gffs.md (i.e. example issues and fixes).

Alternatively, just post the final error in the import2geenuff.py stderr (the Python stack trace, normally the last couple dozen lines), and we'll try and help. 

Cheers,
Ali

**Comment by Toffeeladd** [comment]
Hi Ali,

Apologies for the slow response but I have been doing lots of different runs of Helixer with different parameters. Increasing the --peak-threshold to 0.9 took the gene count down to 78k which is way closer to the reference (62k). I also tried hardmasking the genome which took the gene count down to 51k and then tried them together which took it down to 43k genes. All of these methods had little effect on BUSCO scores. I think I will most likely go with the just the increase in --peak-threshold without hardmasking as I don't want to go below the reference gene number too much. If I want to increase the --peak-threshold further would you recommend trying 0.95 or 1?

I am still very interested in fine tuning the model and I used a different gff3 and reference to do so which fixed the initial problem I had above and the steps seem to run smoothly. The fine_tuning step timed out after 4 days however (without error) but only managed 2ish epochs , I was using default params from the fine tuning example. I can run Helixer with a --batch-size of 512 on my 80GB GPU hpc nodes, would it also likely be the same for the fine_tuning? Also would I need to increase --val-test-batch-size 100 accordingly? Also do I need run 200 epochs or can that be lowered aswell? I am pretty limited to running the gpu nodes for 4 days at a time.

Thank you for your continued help!

Noah

**Comment by alisandra** [comment]
Hi Noah, 

Thanks for the update!

For the peak threshold, you will want to keep it below 1. Certainly halving the remaining distance to one as long as the gene numbers are improving and BUSCO is holding steady is a reasonable strategy (so maybe try 0.95, and if desired then 0.975, and so on). Or if you're trying several in parallel, space them out. For context peak threshold of 1. would be requiring the base-wise predictions to be 100% confident there is a gene there for at least 1bp, which is a threshold rarely, if ever, reached. 

Regarding fine tuning time:

Not finishing in 4 days is much longer than expected. 

There are several things that can cause training to take longer than expected, such as 
1. not actually running on the GPU and instead on the CPU
2. continuously improving on the validation set such that early stopping is not triggered
3. some other bottle neck
  - batch size being way too small
  - io bound
  - out of RAM / swapping
  - or anything that can cause any process to be slow in general
 
The very first thing I would look at to differentiate the above would be the number of epochs completed. With epochs less than say 8 indicating Helixer is training much much slower than expected (e.g. issue 1); less than say 24 indicating Helixer is training slower than expected (e.g. issue 3); and more than that (especially > 100) then potentially implicating issue 2. 

Note these are very rough ball park numbers, so please please take them with a grain of salt. 

I'd also generally take a look at the process once running with e.g. `nvidia-smi` and your favorite `top` variation and make sure Helixer is using the GPU and some CPU, and that the machine isn't completely overloaded and so on.

If you could upload the stderr and stdout logs it would be very helpful for diagnosing this too (I can also get the epochs directly from the log files). 

Finally regarding batch size, yes for the sake of speed you want it to be as large as possible given the available GPU memory. 
Training has to store more numbers than inference (the gradients), so as a rule of thumb the training batch size should be about half of the batch size at validation/inference. Thus you might try `--batch-size 256 --val-test-batch-size 512` for the tuning command. But, that said I'd definitely have still expected it to finish in 4 days with batch size 50. 

Cheers and let me know how it goes,
Ali

**Comment by Toffeeladd** [comment]
Hi Ali,

Ok I will continue to experiment further with the --peak-threshold values. 

Here is my logfile from the last fine_tuning run:
[slurm-1620293.txt](https://github.com/weberlab-hhu/Helixer/files/14237455/slurm-1620293.txt)

Cheers,
Noah

**Comment by alisandra** [comment]
Hi Noah,

Thanks for the log file. So Helixer training completed less than 1.5 epochs. That sounds kinda like it's running on the CPU instead of the GPU pace. I also see that the file contains `libcuda reported version is: NOT_FOUND: was unable to find libcuda.so DSO loaded into this program`; which indicates connecting to GPU issues of some sort. 

That's a bit unexpected using the container. I'll go test things myself with apptainer, as by memory the last instruction set was singularity and it could anyways use an update. I'll do so soonish. 

To help with testing, can you tell me what nvidia driver your system has ([example ways to check](https://linuxconfig.org/how-to-check-nvidia-driver-version-on-your-linux-system))?

Also, sanity check, did inference also run slow (take walltime measured in days, instead of something in the ballpark of 5h)? If not and if inference was timed as expected, are there any potentially-related differences in resources requested or modules loaded (e.g. nividia driver) in the slurm scripts? 

Thanks,
Ali

**Comment by Toffeeladd** [comment]
Hi Ali,

That makes a lot of sense with the run times. My cluster only uses apptainer and does not support singularity unfortunately. The Nvidia driver is taking ages to find out because of the queue times on my clusters GPU nodes to run nividia-smi, ill let you know asap.

Yeah the inference for a 4GB diploid was taking around 4days to complete with a --batch-size 512

Cheers,
noah

**Comment by Toffeeladd** [comment]
Hi Ali,

This is the result of Nvidia-smi:
[nvidia-smi-output.txt](https://github.com/weberlab-hhu/Helixer/files/14309556/nvidia-smi-output.txt)

**Comment by alisandra** [comment]
Hi Noah, 

nvidia driver 525 should work :ballot_box_with_check: 

I was just going through apptainer setup and while I haven't completed the full test yet, a thought: 

You probably need to use `apptainer run` or `apptainer exec` with a `--nv` flag to access the gpu. 

https://apptainer.org/docs/user/main/gpu.html

Best,
Ali

**Comment by Toffeeladd** [comment]
Hi Ali,

I cant believe it was as simple as that, thank you it is now running on the gpu!

Cheers,
Noah

**Comment by alisandra** [comment]
Glad to hear it's working!!!

**Comment by yaoxkkkkk** [comment]
Hi I am using singularity to execuate Helixer to fine-tune a model as mentioned above, but I got a error message at the first step, here is my script:
```
	singularity exec \
		${helixer_path}/helixer-docker_helixer_v0.3.3_cuda_11.8.0-cudnn8.sif import2geenuff.py \
			--fasta /dssg/home/acct-jiang.lu/jiang.lu/Genome_Data/Vitis_vinifera/PN40024/PN40024.T2T/sequence/PN.fa \
			--gff3 /dssg/home/acct-jiang.lu/jiang.lu/Genome_Data/Vitis_vinifera/PN40024/PN40024.T2T/annotation/PN40024.gff3 \
			--db-path Vitis_vinifera.sqlite3 \
			--log-file Vitis_vinifera_import.log \
			--species Vitis_vinifera
```
Here is my log:
```
Start SH helixer pipeline at:
Sun May 26 22:02:21 CST 2024
No config file found, using default values
26-May-24 22:02:24 - INFO: Starting to add genome: Vitis_vinifera
26-May-24 22:02:24 - INFO: FASTA path: /dssg/home/acct-jiang.lu/jiang.lu/Genome_Data/Vitis_vinifera/PN40024/PN40024.T2T/sequence/PN.fa
26-May-24 22:02:24 - INFO: GFF path: /dssg/home/acct-jiang.lu/jiang.lu/Genome_Data/Vitis_vinifera/PN40024/PN40024.T2T/annotation/PN40024.gff3
26-May-24 22:02:24 - INFO: Added coordinate object for FASTA sequence with seqid PN1 to the queue
26-May-24 22:02:24 - INFO: Added coordinate object for FASTA sequence with seqid PN2 to the queue
26-May-24 22:02:24 - INFO: Added coordinate object for FASTA sequence with seqid PN3 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN4 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN5 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN6 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN7 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN8 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN9 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN10 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN11 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN12 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN13 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN14 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN15 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN16 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN17 to the queue
26-May-24 22:02:25 - INFO: Added coordinate object for FASTA sequence with seqid PN18 to the queue
26-May-24 22:02:26 - INFO: Added coordinate object for FASTA sequence with seqid PN19 to the queue
26-May-24 22:02:27 - INFO: Starting to parse the GFF file
Aborting due to error, attempt so far saved at Vitis_vinifera.sqlite3.partial for debugging purposes
Traceback (most recent call last):
  File "/usr/local/bin/import2geenuff.py", line 122, in <module>
    main(args)
  File "/usr/local/bin/import2geenuff.py", line 95, in main
    controller.add_genome(paths.fasta_in, paths.gff_in, genome_args)
  File "/usr/local/lib/python3.8/dist-packages/geenuff/applications/importer.py", line 892, in add_genome
    raise e
  File "/usr/local/lib/python3.8/dist-packages/geenuff/applications/importer.py", line 884, in add_genome
    self.add_gff(gff_path, clean=clean_gff)
  File "/usr/local/lib/python3.8/dist-packages/geenuff/applications/importer.py", line 959, in add_gff
    self.latest_fasta_importer.mk_mapper(gff_file)
  File "/usr/local/lib/python3.8/dist-packages/geenuff/applications/importer.py", line 1019, in mk_mapper
    raise NotImplementedError("Still need to implement backward match if fasta IDs "
NotImplementedError: Still need to implement backward match if fasta IDs are subset of gff IDs
Command failed with exit status 1.
SH helixer pipeline finished at:
Sun May 26 22:02:28 CST 2024
```
Can you help me with it?

**Comment by JiantaoZhao426** [comment]
Hi,

I'm not sure why you get this error. The simplest way to debug this error might be to first run the example data to see whether the software is installed properly or not. If you can run the example data, which might give you some ideas about how to fix this.

Jiantao


---------------------------------------------------------
Postdoc, Boyce Thompson Institute
Cornell University
533 Tower Road, Ithaca, NY, 14850
Email: ***@***.***
________________________________

**Comment by alisandra** [comment]
Hi yaoxkkkkk,

The error: 
`NotImplementedError: Still need to implement backward match if fasta IDs are subset of gff IDs`

Is descriptive, it simply means there were extra sequence IDs parsed from the GFF file that weren't in the fasta file. I think your checks were going in the right direction. Always a good idea to stop and check why a discrepancy like that is occurring. I would guess, but do not know without seeing the data, that the `/PN/` part of your first awk command is filtering the mismatched IDs and preventing you from seeing the discrepancy.

If you provide Helixer with a GFF filtered in a similar fashion you should be able to continue with fine tuning, should you still want to.
