### ISSUE TITLE
Issues with Gymnosperms

### ISSUE THREAD

**Issue by nhartwic** [weberlab-hhu/Helixer#118]
My lab recently picked up Helixer and have found that it works extremely well. So far the only thing it has performed poorly on is Gymnosperm genomes. Admittedly, testing has been somewhat limited here, I've ran a publicly available [Gnetum](https://datadryad.org/stash/dataset/doi:10.5061/dryad.0vm37) genome, a not yet public Ephedra genome, and am in the process of testing on [Giant Redwood](https://bioinformatics.psb.ugent.be/plaza/versions/plaza_v5_dicots/organism/view/Sequoiadendron+giganteum).

| Assembly | Busco C Ref | Busco C Helixer |
| ---------- | -------------: | ----------------: |
| Gnetum | 90.6% | 76.3% |
| Ephedra | 82.8% | 48.0% |
| Redwood | TODO | TODO |

...Any thoughts/advice? What data would be needed to fine tune the land plant model for gymnosperms or train a new model entirely?

**Comment by nhartwic** [comment]
Closing this since you seem to have reasonable docs for training already. Not sure how I missed them earlier.

**Comment by alisandra** [comment]
Thanks! Feel free to reach out at any point if that's helpful for fine tuning or training.
