### ISSUE TITLE
results from web tool not sent

### ISSUE THREAD

**Issue by jasonwjohns** [weberlab-hhu/Helixer#124]
Hello,

Yesterday I submitted a job through the web tool for a land plant with the 20240328.dmAquExim1.NCBI.a_ctg.fasta.gz, and input my email address: johnswjason@gmail.com. Yesterday I could see that the job was pending at the bottom of the job submission page, but I don't see any information there today. I have no idea how long this tool takes to run, so it's very possible that it's still queued or maybe still running, but I thought I would inquire. Would you mind clarifying for me?

Thank you!
Jason

**Comment by jasonwjohns** [comment]
Update: my first job submission of two came in yesterday evening and it looks awesome! For context, we work with columbines (Aquilegia), and have an annotation from A. coerulea 'Goldsmith' done with RNAseq and ESTs in 2015. We used Liftoff on a new genome assembly for a close relative, A. eximia, which seemed to work well. We then ran Helixer on A. eximia. I only looked at a few genes, but the gene structure matches our previous annotations nearly perfectly! The only parts that differ are the UTRs.

In case they are going to clog the system, I thought I would let you know, my advisor got a bit overeager (even more than me) and submitted a few jobs between yesterday and today, which we don't need. They are all under his email, sahodges@ucsb.edu. One of the jobs was the demo file, A. lyrata, and the others were redundant with a job I submitted yesterday for a marine flowering plant, Phyllospadix torreyi. I have attached screen shots of the info associated with those jobs. 

I would still like my remaining job to run, but if you happen to see this in time, you can cancel the A. lyrata job and the two jobs associated with the attached screen shots. I apologize for any inconvenience this may cause.
![image (10)](https://github.com/weberlab-hhu/Helixer/assets/36780700/c10c289c-180e-4a5e-85e8-648973bcf4a9)
![image (11)](https://github.com/weberlab-hhu/Helixer/assets/36780700/e86cf38b-ba93-44fc-8aac-4cd4b3bbfe25)


Thank you!

**Comment by alisandra** [comment]
Hi jasonwjohns,

Many thanks for this message and the update. Glad it worked out!
