### ISSUE TITLE
Helixer and the protein related domain

### ISSUE THREAD

**Issue by LeoVincenzi** [weberlab-hhu/Helixer#129]
Dear developers,
I have a curiosity about Helixer software. Performing structural annotation with _ab initio_ predictions (with pipelines like BRAKER, AUGUSTUS, etc..), usually requires the additional filtering of the annotated genes by protein-related domains by applying tools such as Interproscan. 
How about Helixer? Should we perform this kind of analysis also here or your software annotation already take into account such information?

Thanks,
Leo

**Comment by alisandra** [comment]
Hi Leo, 

Helixer has no internal filtering by protein domains. I could ramble on about things that might be different from the pipelines but the only real answer is: I have not tested the efficacy of this with Helixer annotations. If you do so, reporting the results would be appreciated and likely of interest to others. 

Cheers,
Alisandra
