### ISSUE TITLE
How does helixer evaluate performance when predicting genomes?

### ISSUE THREAD

**Issue by ZhangPY-bioinformatics** [weberlab-hhu/Helixer#131]
When I was using helixer, I found that HelixerPost would output the precision, recall and F1 score for each seq_id. 
But this confused me. I only provided the genome sequence to be predicted, so how to compare it with the label when predicting? In my understanding, it seems that there must be a reference annotation file for performance evaluation?

**Comment by alisandra** [comment]
Yeah, you can ignore this, it's important during tool development and training when a reference is available, but meaningless during inference.
