### ISSUE TITLE
Web tool doesn't working well?

### ISSUE THREAD

**Issue by Ryohei-Fujita** [weberlab-hhu/Helixer#141]
I have been using the Helixer web tool to obtain annotation information from the genome sequence of the Lonicera japonica jyh strain. 
The genome sequence I am using is available at the following link:

https://ngdc.cncb.ac.cn/gwh/Assembly/660/show
(While a GFF file is available on this page, I am specifically trying to generate a new GFF file using Helixer.)

When I submit the genome to Helixer in these days, the job status turns to "FINISHED" after about 30 seconds. However, when I attempt to download the results, the page shows as follows:
>**Not Found**
>The requested URL /projects/Helixer_output/GSA-e8d33acace3accd7b7d52624110ef09.zip was not found on this server.
>
>Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Strangely, the tool works correctly with Oryza sativa sequences, and I was able to successfully use Helixer with the Lonicera japonica genome about a week ago. I haven't changed any steps in my submission process since then.

Could you please help me resolve this issue?

Thank you in advance.

**Comment by felicitas215** [comment]
Hi, thank you for raising this issue. We updated the web version recently and ran into memory issues, so the submitted jobs were killed by the system before completing. This issue is fixed now. Please let us know if your job now runs successfully. If so, I will close this issue.

**Comment by Ryohei-Fujita** [comment]
Thank you for your response.
I submitted my job and it works successfully.

**Comment by Ryohei-Fujita** [comment]
Thank you for your response.
I submitted my job and it works successfully.
