### ISSUE TITLE
model  file  cannot download

### ISSUE THREAD

**Issue by xiaoxinbioinfo** [weberlab-hhu/Helixer#144]
Hello,

When I was using this software, I found that I could not get the model file from the model download link  [https://uni-duesseldorf.sciebo.de/s/lQTB7HYISW71Wi0](https://uni-duesseldorf.sciebo.de/s/lQTB7HYISW71Wi0) . 

The web page opened like this. 
![image](https://github.com/user-attachments/assets/6f0c4822-1b27-463f-bb7a-27ec10aa9de8)

How to deal with this problem?

**Comment by felicitas215** [comment]
Hi,
the models location changed recently, we just forgot to update the link if you want to download them manually. There will be a change in the README soon. The new link to the models is: https://zenodo.org/records/10836346.

**Comment by felicitas215** [comment]
The README was updated to link to zenodo.
