### ISSUE TITLE
Tensorflow installation incompatible with requirements

### ISSUE THREAD

**Issue by MatteoSchiavinato** [weberlab-hhu/Helixer#149]
I am installing helixer following the manual installation guideline: 
https://github.com/weberlab-hhu/Helixer/blob/main/docs/manual_install.md

The procedure suggests: 
`tensorflow-gpu==2.7.0`

However, this version seems to be incompatible with some of the packages listed in requirements when using python v3.10 (specifically, tensorflow, keras and tensorflow addons).

Is there any reason why this particular version is needed, and not, for example, tensorflow-gpu v2.11.0?

**Comment by MatteoSchiavinato** [comment]
Far from being the solution, but I have managed to complete the installation with:

```
pip install -r requirements.3.10.txt
pip install tensorflow==2.11.0 tensorflow-gpu==2.11.0 tensorflow-addons==0.18.0 keras==2.11.0
```

The testing command only returns a warning, with no errors. The exit code with the warnings is however 2, not 0, which is a bit annoying because the docker build fails. Thought it was worth reporting.

**Comment by felicitas215** [comment]
Hi,
thank you for reporting this issue. We updated manual install documentation to the newer way of installing the tensorflow GPU requirements. This method is compatible with the versions from the `requirements.3.10.txt`.

**Comment by MatteoSchiavinato** [comment]
Are these two installation commands:
```
# install tensorflow 
RUN python3 -m pip install --no-cache-dir --upgrade --target /usr/lib/python3.10/ tensorflow[and-cuda]

# install tensorRT 
RUN python3 -m pip install --no-cache-dir --upgrade --target /usr/lib/python3.10/ tensorrt
```

Still needed now? Or are they included in the requirements already?

**Comment by felicitas215** [comment]
The `tensorrt` package is not strictly needed anymore, but `tensorflow[and-cuda]` is necessary to install the GPU requirements additionally to the CPU tensorflow version in the requirements.3.10.txt.

**Comment by felicitas215** [comment]
However, these requirements don't seem to be necessary to build the Docker image. The containers (either nvidia docker runtime or singularity) seem to handle that, since both packages aren't mentioned in the provided Dockerfile (https://github.com/gglyptodon/helixer-docker/blob/main/Dockerfile).
