### ISSUE TITLE
`HelixerModel.py` not behaving as `Helixer.py`, quickly dying after being run 

### ISSUE THREAD

**Issue by MatteoSchiavinato** [weberlab-hhu/Helixer#155]
**Describe the bug**
The `HelixerModel.py` script, suggested in the 3-step advanced usage of the tool, dies shortly after being run. It does not print an error, but rather a warning related to TensorFlow which does not seem like something that would affect the run. 

It just dies silently, even using `--debug -v`. 

**To Reproduce**
This is the command I ran:

```
    python3 /opt/Helixer/helixer/prediction/HelixerModel.py \
    --load-model-path ${helixer_model} \
    --save-model-path ${alias}_bestmodel.h5 \
    --test-data ${alias}.h5 \
    --overlap \
    --val-test-batch-size 32 \
    -v \
    --compression lzf \
    --cpus 50 \
    --workers 4 \
    --prediction-output-path predictions_h5
```

I have run it on a machine without GPU, as for `Helixer.py`, this would mean it would only use the CPUs available. 

**Error**
```
/usr/lib/python3.10/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
```

**Expected behavior**
I would expect it to do one of the two:
- use only available CPUs when GPU is not available, as the main script does 
- throw out an error saying that this particular script can only be used when GPU is available 

**Environment (please complete the following information):**
Ubuntu 22.04 docker image (see issue https://github.com/weberlab-hhu/Helixer/issues/154)

**Additional context**
- The `Helixer.py` script works fine on this machine. 
- The same behavior pops out if I reduce CPUs and set workers to 0

**Comment by MatteoSchiavinato** [comment]
I'm sure this is all the result of using `HelixerModel.py` instead of `HybridModel.py`. I was indeed snooping through the argparse declarations to find parameters to use, and was confused by many of them. 

Happy that it was just this!

**Comment by MatteoSchiavinato** [comment]
What I was trying to achieve was to follow through the 3-step running mode that is explained in the docs. I simply confused the script name, apparently. 

However, I am a bit confused by the parameters, since both `--load-model-path` and `--save-model-path` are present. Is there any specific documentation on them, that I may read? I haven't found it so far (sorry)

**Comment by felicitas215** [comment]
If you click on the links in the README that mention the 'Helixer options documentation' (which will bring you here: https://github.com/weberlab-hhu/Helixer/blob/main/docs/helixer_options.md), you will find an overview of all the main files and their options.
