### ISSUE TITLE
Test (and probably bugfix) phase encoding where we don't start with phase 0 

### ISSUE THREAD

**Issue by alisandra** [weberlab-hhu/Helixer#53]
i.e. 
- when there was a partial model in the gff and it started with phase != 0
- during super chunking / splitting into write_by
  - (currently test_super_chunking4write does catch this, but potentially should be done a bit more formally)

(and sorry if I'm missing something, if it's already there and I missed it)

**Comment by soi** [comment]
ok, so the problem is that we should not start with phase 0 in first cds due to an impartial gene model and instead take the phase from the gff?

**Comment by alisandra** [comment]
yes, that, and for the second super chunking point we can either 1) avoid ever splitting within the CDS, or 2) handle a cds that started outside of the chunk, which might be more of a pain than it's worth.

**Comment by soi** [comment]
I'm going to try to fix the phase encoding then

**Comment by alisandra** [comment]
Ok, great, thanks! 

Was looking at the code for this last night (to ID what was going on), so if it gives any trouble, just ping me.

**Comment by alisandra** [comment]
The "during super chunking / splitting into write_by" bit is also now patched (avoided splitting in CDS entirely)
