### ISSUE TITLE
Helixer.py produces empty GFF file for very small Fasta Input

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/Helixer#83]
[test.fa.txt](https://github.com/weberlab-hhu/Helixer/files/8694635/test.fa.txt)

Helixer.py produced an 0 Byte GFF file as output for this input despite calling the process successful on the cli. Larger input files worked.

**Comment by alisandra** [comment]
Thanks, I finally took a look, and I got output with the provided test.fa.txt, (using either land_plant_v0.3_a_0100.h5
or vertebrate_v0.3_m_0100.h5). 

Did you maybe fix it but not close the issue?
Else, I'd hazard a guess that maybe the model used before simply hadn't predicted a gene there.

In any case, HelixerPost should now include the pragmas for sequence start, etc, regardless of a sequence
without a gene; so this sort of thing would now be a less cryptic error. 

Closing now in any case, do reopen if I'm missing something.
